version: 2
jobs:
  build:
    docker:
      - image: node:10

    steps:
      - checkout

      - run:
          name: Setup VirtualEnv
          command: |
            echo "'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV"
            echo "'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV"

      - run:
          name: Run Tests 
          command: |
            echo "npm test"

      - run:
          name: Build and push Docker image
          command: |
            echo "docker build -t ariv3ra/$IMAGE_NAME:$TAG ."
            echo "$DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin"
            echo "docker push ariv3ra/$IMAGE_NAME:$TAG"

      - run:
          name: Deploy App
          command: |
            echo "ssh -o StrictHostKeyChecking=no user@herokuserver /bin/bash ./deploy_app.sh surfersamu/$IMAGE_NAME:$TAG"
